### ISSUE TITLE
problem about DataLoader.py line 223.

### ISSUE THREAD

**Issue by szyszyzys** [zjs123/DTGB#1]
Thank you for providing this excellent dataset!

I noticed a potential issue in DataLoader.py on line 223. It appears that this line may be causing all the edge features to be dropped:
`
    rel_num = cat_num
    `
Could you please take a look? Thank you!

**Comment by zjs123** [comment]
Hi, thank you for your interest in this work. We use this code to control whether categories or text are used as edge features, as part of an ablation experiment (In some datasets, such as Enron, using categories as edge features may result in better edge classification performance). To use text embeddings as edge features, you can comment out this line.

**Comment by szyszyzys** [comment]
Thanks for the response :)
