### ISSUE TITLE
Discrepancies in GDELT Dataset

### ISSUE THREAD

**Issue by Zening-Li** [zjs123/DTGB#2]
Hi Jiasheng,
Thank you for sharing the Dynamic Text-Attributed Graph dataset online. I would like to use some datasets from your paper, but I noticed some discrepancies between the data in the repository and the description in the paper about the dataset GDELT, such as the number of nodes, edges, and timestamps. Could you kindly confirm if this is the correct version of the dataset used in your research, or is there some other problem?
Thanks again for your great work, and I look forward to your response.

**Comment by Zening-Li** [comment]
The number of nodes, edges and timestamps are 5849, 943956 and 2403 respectively.

**Comment by zjs123** [comment]
Hi, Zening, thanks for your kind reminder. I have updated the latest version of the GDELT dataset. Good luck with your research.
